### ISSUE TITLE
Can't build with README instructions

### ISSUE THREAD

**Issue by winhamwr** [PolicyStat/vegan#1]
Looks like maybe a `browserify-middleware` requirement is missing?

```shell
vegan$ npm install
npm WARN package.json vegan@1.0.0 No repository field.
get-port@1.0.0 node_modules/get-port

xtend@4.0.0 node_modules/xtend

keycode@2.1.0 node_modules/keycode

validate.io-positive-integer@1.0.0 node_modules/validate.io-positive-integer
└── validate.io-integer@1.0.5 (validate.io-number@1.0.3)

express@4.13.1 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.0
├── utils-merge@1.0.0
├── methods@1.1.1
├── cookie@0.1.3
├── range-parser@1.0.2
├── cookie-signature@1.0.6
├── fresh@0.3.0
├── path-to-regexp@0.1.6
├── content-type@1.0.1
├── vary@1.0.0
├── parseurl@1.3.0
├── etag@1.7.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── qs@4.0.0
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, mime@1.3.4, ms@0.7.1, http-errors@1.3.1)
├── accepts@1.2.10 (negotiator@0.5.3, mime-types@2.1.2)
└── type-is@1.6.4 (media-typer@0.3.0, mime-types@2.1.2)

array-includes@2.0.0 node_modules/array-includes
├── define-properties@1.1.0 (foreach@2.0.5, object-keys@1.0.5)
└── es-abstract@1.2.1 (is-callable@1.0.4, es-to-primitive@1.0.0)

react@0.13.3 node_modules/react
└── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)

standard@4.5.2 node_modules/standard
├── get-stdin@4.0.1
├── uniq@1.0.1
├── find-root@0.1.1
├── eslint-config-standard-react@1.0.1
├── eslint-config-standard@3.4.1
├── run-parallel@1.1.2
├── ignore@2.2.15
├── minimist@1.1.1
├── pkg-config@1.1.0 (debug-log@1.0.0)
├── dezalgo@1.0.3 (wrappy@1.0.1, asap@2.0.3)
├── eslint-plugin-react@2.6.4
├── glob@5.0.13 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── standard-format@1.3.9 (esformatter-spaced-lined-comment@2.0.1, stdin@0.0.1, esformatter-quotes@1.0.2, esformatter-eol-last@1.0.0, minimatch@2.0.8, esformatter-semicolon-first@1.1.0, esformatter-literal-notation@1.0.1, esformatter@0.7.1)
└── eslint@0.24.0 (escape-string-regexp@1.0.3, path-is-absolute@1.0.0, user-home@1.1.1, object-assign@2.1.1, strip-json-comments@1.0.2, xml-escape@1.0.0, estraverse-fb@1.3.1, globals@8.2.0, estraverse@4.1.0, text-table@0.2.0, debug@2.2.0, mkdirp@0.5.1, chalk@1.1.0, minimatch@2.0.8, optionator@0.5.0, espree@2.0.4, is-my-json-valid@2.12.0, doctrine@0.6.4, concat-stream@1.5.0, js-yaml@3.3.1, inquirer@0.8.5, escope@3.1.0)
wes@wes-Gazelle-Professional:~/policystat/workspace/vegan$ node test/bench/server

module.js:340
    throw err;
          ^
Error: Cannot find module 'browserify-middleware'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/wes/policystat/workspace/vegan/test/bench/server/start-express.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
wes@wes-Gazelle-Professional:~/policystat/workspace/vegan$ which node
/home/wes/.nvm/v0.10.39/bin/node
```

**Comment by mightyiam** [comment]
Thank you, @winhamwr. You're free to try it.
